name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - droplet

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Login to DigitalOcean Container Registry
        if: github.ref == 'refs/heads/droplet'
        uses: digitalocean/container-registry-login@v1
        with:
          registry: registry.digitalocean.com/rawr
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DOCR_PASSWORD }}
      
      - name: Build and push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ricklon/disco_chat:latest
      
      - name: Build and push Docker image to DigitalOcean Container Registry
        if: github.ref == 'refs/heads/droplet'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/rawr/disco_chat:latest
