name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - droplet

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Install and configure doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Login to DigitalOcean Container Registry
        if: github.ref == 'refs/heads/droplet'
        run: |
          doctl registry login  --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
      
      - name: Build and push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ricklon/disco_chat:latest
      
      - name: Build and push Docker image to DigitalOcean Container Registry
        if: github.ref == 'refs/heads/droplet'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/rawr/disco_chat:latest
